# Spring Boot Project Port
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-exception: false
    include-message: never
    include-stacktrace: never
    include-binding-errors: never

spring:
  # Log Resolved Exception
  mvc:
    log-resolved-exception: true

  # Set the time zone for the database connection to UTC
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC

    # Use Hibernate to automatically create tables based on entity classes
    hibernate:
      ddl-auto: create
      show-sql: true

  # Validation
  validation:
    enabled: true

  # Configure the MySQL database connection
  datasource:
    url: jdbc:mysql://localhost:3306/yeolmae
    username: root
    password: 4937
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  # JWT
  jwt:
    secret-key: 510f3c740da678e3b6c273be5369157ab2e095815ce2d082ad002e5d00d72a94054c2bc0ee2ce638ab53ff825cc14d1b85c8f25eae38760c73948f1a17a2aeab
    # Access Token and Refresh Token Validity Period
    # 1,800,000ms = 30 minutes
    # 1,209,600,000ms = 14 days
    token-validity-in-seconds:
      access-token: 1800000
      refresh-token: 1209600000

  swagger:
    patterns:
      - /swagger-config
      - /swagger-ui.html
      - /swagger-ui/*
      - /v3/api-docs
      - /v3/api-docs/*

#File Upload
resource:
  file:
    url: /resources/files
    path: ${user.dir}/cloud

# Configure Swagger UI and generate OpenAPI documentation
springdoc:
  version: v1.0.0
  packages-to-scan: com.capstone.yeolmaeTeamProject
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8